# Generated by Django 5.1.3 on 2024-11-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_haridor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haridor',
            name='rasm',
            field=models.ImageField(upload_to='haridor'),
        ),
    ]
